apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: ksvc-httpd
  namespace: apache
  labels:
    app.kubernetes.io/component: ksvc-httpd
    app.kubernetes.io/instance: ksvc-httpd
    app.kubernetes.io/name: httpd
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: httpd
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/component: ksvc-httpd
        app.kubernetes.io/instance: ksvc-httpd
        deployment: httpd
    spec:
      containerConcurrency: 0
      volumes:
        - name: sec-ctx-vol
          emptyDir: {}
      initContainers:
        - name: init-httpd
          image: >-
            registry.redhat.io/rhel8/httpd-24
          command:
            - sh
            - '-c'
            - echo "v1" > /var/www/html/index.html
          resources: {}
          volumeMounts:
            - name: sec-ctx-vol
              mountPath: /var/www/html
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      containers:
        - name: httpd
          image: >-
            registry.redhat.io/rhel8/httpd-24
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: sec-ctx-vol
              mountPath: /var/www/html
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent      
      enableServiceLinks: false
      timeoutSeconds: 300
  traffic:
    - latestRevision: true
      percent: 100
